server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shashith95/spring-app-config
          clone-on-start: true
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8080/eureka}